shared_buffers = 4GB
effective_cache_size = 14GB
work_mem = 16MB
maintenance_work_mem = 256MB

checkpoint_timeout = 15min
max_wal_size = 2GB
min_wal_size = 1GB
wal_compression = on
wal_buffers = 16MB

bgwriter_delay = 200ms
bgwriter_lru_maxpages = 1000

random_page_cost = 1.1
effective_io_concurrency = 200

max_connections = 50

listen_addresses = '*'

logging_collector = on
log_min_duration_statement = 1000