[Interface]
Address = 10.99.0.1/24
ListenPort = 51820
PrivateKey = IF3vcl6JHwI8eMDbDSd120D2eWm71fHXd52KIBaAU1I=

[Peer]
PublicKey = D+tYQ8OQCWDWddRkgCOnyU5f1TG+xFjJJtrO8SNurWw=
AllowedIPs = 10.99.0.2/32

[Peer]
PublicKey = igIU5OvJyOkMZa333ox6q6D7bdSzJtpeSPcSw8+Hggg=
AllowedIPs = 10.99.0.3/32
