qwen3-0.6b:
  model:
    name_or_path: Qwen/Qwen3-0.6B
    dtype: auto
    device_map: auto
  generation:
    temperature: 0.1
    top_p: 0.8
    top_k: 20
    min_p: 0.0
    max_new_tokens: 256
    presence_penalty: 1.5
  chat_template:
    enable_thinking: false

qwen2.5-0.5b-instruct:
  model:
    name_or_path: Qwen/Qwen2.5-0.5B-Instruct
    dtype: auto
    device_map: auto
  generation:
    temperature: 0.1
    top_p: 0.9
    max_new_tokens: 256
