use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

#[derive(Default)]
pub struct Metrics {
    pub inbound_ping: AtomicU64,
    pub inbound_find_node: AtomicU64,
    pub inbound_get_peers: AtomicU64,
    pub inbound_announce_peer: AtomicU64,
    pub inbound_invalid: AtomicU64,
    pub inbound_find_node_bep42: AtomicU64,
    pub inbound_find_node_random: AtomicU64,
    pub inbound_get_peers_bep42: AtomicU64,
    pub inbound_get_peers_random: AtomicU64,
    pub inbound_announce_bep42: AtomicU64,
    pub inbound_announce_random: AtomicU64,
    pub inbound_announce_invalid_token: AtomicU64,
    pub inbound_announce_valid: AtomicU64,
    pub tokens_issued: AtomicU64,
    pub infohashes_harvested: AtomicU64,
    pub unique_infohashes: AtomicU64,
    pub outbound_queries: AtomicU64,
    pub outbound_timeouts: AtomicU64,
    pub tx_table_len: AtomicU64,
    pub routing_table_len: AtomicU64,
    pub verify_attempts: AtomicU64,
    pub verify_success: AtomicU64,
    pub verify_fail: AtomicU64,
    pub verify_timeouts: AtomicU64,
    pub fetch_attempts: AtomicU64,
    pub source_queries: AtomicU64,
    pub source_responses: AtomicU64,
    pub source_peers_returned: AtomicU64,
    pub send_dropped: AtomicU64,
    // Granular failure counters
    pub source_timeout: AtomicU64,
    pub source_no_peers: AtomicU64,
    pub source_all_timeout: AtomicU64,
    pub fetch_connect_timeout: AtomicU64,
    pub fetch_connect_io: AtomicU64,
    pub fetch_handshake: AtomicU64,
    pub fetch_no_extension: AtomicU64,
    pub fetch_reject: AtomicU64,
    pub fetch_bad_piece: AtomicU64,
    pub fetch_io: AtomicU64,
    pub sha1_mismatch: AtomicU64,
    // Peer cache metrics
    pub peer_cache_size: AtomicU64,
    pub peer_cache_hits: AtomicU64,
    pub peer_cache_evictions: AtomicU64,
    // Source peer quality metrics
    pub source_returned_peers: AtomicU64,
    pub source_filtered_by_cache: AtomicU64,
    pub source_no_values: AtomicU64,
    // Pipelined source lookup termination
    pub source_deadline_hits: AtomicU64,
    pub source_deadline_peers: AtomicU64,
    // Announce direct-fetch metrics
    pub announce_attempts: AtomicU64,
    pub announce_success: AtomicU64,
    // Transport metrics
    pub tcp_attempts: AtomicU64,
    pub utp_attempts: AtomicU64,
    pub tcp_connect_ok: AtomicU64,
    pub utp_connect_ok: AtomicU64,
    pub tcp_metadata_ok: AtomicU64,
    pub utp_metadata_ok: AtomicU64,
    // Per-transport actual connect success (regardless of race winner)
    pub tcp_connect_actual: AtomicU64,
    pub utp_connect_actual: AtomicU64,
    // Connect-vs-metadata accounting
    pub connect_ok_no_metadata: AtomicU64,
    pub metadata_failed_io: AtomicU64,
    pub metadata_failed_silent: AtomicU64,
    pub metadata_timeout: AtomicU64,
    // Walker metrics
    pub walker_steps: AtomicU64,
    pub walker_queries: AtomicU64,
    pub walker_ok: AtomicU64,
    pub walker_nodes_returned: AtomicU64,
    pub walker_self_target: AtomicU64,
    pub walker_random_target: AtomicU64,
    pub walker_sybil_target: AtomicU64,
    // Routing insert metrics
    pub routing_insert_calls: AtomicU64,
    pub routing_nodes_added: AtomicU64,
    pub routing_buckets_used: AtomicU64,
    pub routing_new_ids: AtomicU64,
    pub routing_rejected: AtomicU64,
    // Logging metrics
    pub log_dropped: Arc<AtomicU64>,
}

impl Metrics {
    pub fn new(log_dropped: Arc<AtomicU64>) -> Self {
        Metrics {
            log_dropped,
            ..Metrics::default()
        }
    }
}

pub trait Add1 {
    fn add(&self, n: u64);
}

impl Add1 for AtomicU64 {
    fn add(&self, n: u64) {
        self.fetch_add(n, Ordering::Relaxed);
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct Snapshot {
    pub inbound_ping: u64,
    pub inbound_find_node: u64,
    pub inbound_get_peers: u64,
    pub inbound_announce_peer: u64,
    pub inbound_invalid: u64,
    pub inbound_find_node_bep42: u64,
    pub inbound_find_node_random: u64,
    pub inbound_get_peers_bep42: u64,
    pub inbound_get_peers_random: u64,
    pub inbound_announce_bep42: u64,
    pub inbound_announce_random: u64,
    pub inbound_announce_invalid_token: u64,
    pub inbound_announce_valid: u64,
    pub tokens_issued: u64,
    pub infohashes_harvested: u64,
    pub unique_infohashes: u64,
    pub outbound_queries: u64,
    pub outbound_timeouts: u64,
    pub tx_table_len: u64,
    pub routing_table_len: u64,
    pub verify_attempts: u64,
    pub verify_success: u64,
    pub verify_fail: u64,
    pub verify_timeouts: u64,
    pub fetch_attempts: u64,
    pub source_queries: u64,
    pub source_responses: u64,
    pub source_peers_returned: u64,
    pub send_dropped: u64,
    pub source_timeout: u64,
    pub source_no_peers: u64,
    pub source_all_timeout: u64,
    pub fetch_connect_timeout: u64,
    pub fetch_connect_io: u64,
    pub fetch_handshake: u64,
    pub fetch_no_extension: u64,
    pub fetch_reject: u64,
    pub fetch_bad_piece: u64,
    pub fetch_io: u64,
    pub sha1_mismatch: u64,
    pub peer_cache_size: u64,
    pub peer_cache_hits: u64,
    pub peer_cache_evictions: u64,
    pub source_returned_peers: u64,
    pub source_filtered_by_cache: u64,
    pub source_no_values: u64,
    pub source_deadline_hits: u64,
    pub source_deadline_peers: u64,
    pub announce_attempts: u64,
    pub announce_success: u64,
    pub tcp_attempts: u64,
    pub utp_attempts: u64,
    pub tcp_connect_ok: u64,
    pub utp_connect_ok: u64,
    pub tcp_metadata_ok: u64,
    pub utp_metadata_ok: u64,
    pub tcp_connect_actual: u64,
    pub utp_connect_actual: u64,
    pub connect_ok_no_metadata: u64,
    pub metadata_failed_io: u64,
    pub metadata_failed_silent: u64,
    pub metadata_timeout: u64,
    pub walker_steps: u64,
    pub walker_queries: u64,
    pub walker_ok: u64,
    pub walker_nodes_returned: u64,
    pub walker_self_target: u64,
    pub walker_random_target: u64,
    pub walker_sybil_target: u64,
    pub routing_insert_calls: u64,
    pub routing_nodes_added: u64,
    pub routing_buckets_used: u64,
    pub routing_new_ids: u64,
    pub routing_rejected: u64,
    pub log_dropped: u64,
}

impl Metrics {
    pub fn snapshot(&self) -> Snapshot {
        Snapshot {
            inbound_ping: self.inbound_ping.load(Ordering::Relaxed),
            inbound_find_node: self.inbound_find_node.load(Ordering::Relaxed),
            inbound_get_peers: self.inbound_get_peers.load(Ordering::Relaxed),
            inbound_announce_peer: self.inbound_announce_peer.load(Ordering::Relaxed),
            inbound_invalid: self.inbound_invalid.load(Ordering::Relaxed),
            inbound_find_node_bep42: self.inbound_find_node_bep42.load(Ordering::Relaxed),
            inbound_find_node_random: self.inbound_find_node_random.load(Ordering::Relaxed),
            inbound_get_peers_bep42: self.inbound_get_peers_bep42.load(Ordering::Relaxed),
            inbound_get_peers_random: self.inbound_get_peers_random.load(Ordering::Relaxed),
            inbound_announce_bep42: self.inbound_announce_bep42.load(Ordering::Relaxed),
            inbound_announce_random: self.inbound_announce_random.load(Ordering::Relaxed),
            inbound_announce_invalid_token: self
                .inbound_announce_invalid_token
                .load(Ordering::Relaxed),
            inbound_announce_valid: self.inbound_announce_valid.load(Ordering::Relaxed),
            tokens_issued: self.tokens_issued.load(Ordering::Relaxed),
            infohashes_harvested: self.infohashes_harvested.load(Ordering::Relaxed),
            unique_infohashes: self.unique_infohashes.load(Ordering::Relaxed),
            outbound_queries: self.outbound_queries.load(Ordering::Relaxed),
            outbound_timeouts: self.outbound_timeouts.load(Ordering::Relaxed),
            tx_table_len: self.tx_table_len.load(Ordering::Relaxed),
            routing_table_len: self.routing_table_len.load(Ordering::Relaxed),
            verify_attempts: self.verify_attempts.load(Ordering::Relaxed),
            verify_success: self.verify_success.load(Ordering::Relaxed),
            verify_fail: self.verify_fail.load(Ordering::Relaxed),
            verify_timeouts: self.verify_timeouts.load(Ordering::Relaxed),
            fetch_attempts: self.fetch_attempts.load(Ordering::Relaxed),
            source_queries: self.source_queries.load(Ordering::Relaxed),
            source_responses: self.source_responses.load(Ordering::Relaxed),
            source_peers_returned: self.source_peers_returned.load(Ordering::Relaxed),
            send_dropped: self.send_dropped.load(Ordering::Relaxed),
            source_timeout: self.source_timeout.load(Ordering::Relaxed),
            source_no_peers: self.source_no_peers.load(Ordering::Relaxed),
            source_all_timeout: self.source_all_timeout.load(Ordering::Relaxed),
            fetch_connect_timeout: self.fetch_connect_timeout.load(Ordering::Relaxed),
            fetch_connect_io: self.fetch_connect_io.load(Ordering::Relaxed),
            fetch_handshake: self.fetch_handshake.load(Ordering::Relaxed),
            fetch_no_extension: self.fetch_no_extension.load(Ordering::Relaxed),
            fetch_reject: self.fetch_reject.load(Ordering::Relaxed),
            fetch_bad_piece: self.fetch_bad_piece.load(Ordering::Relaxed),
            fetch_io: self.fetch_io.load(Ordering::Relaxed),
            sha1_mismatch: self.sha1_mismatch.load(Ordering::Relaxed),
            peer_cache_size: self.peer_cache_size.load(Ordering::Relaxed),
            peer_cache_hits: self.peer_cache_hits.load(Ordering::Relaxed),
            peer_cache_evictions: self.peer_cache_evictions.load(Ordering::Relaxed),
            source_returned_peers: self.source_returned_peers.load(Ordering::Relaxed),
            source_filtered_by_cache: self.source_filtered_by_cache.load(Ordering::Relaxed),
            source_no_values: self.source_no_values.load(Ordering::Relaxed),
            source_deadline_hits: self.source_deadline_hits.load(Ordering::Relaxed),
            source_deadline_peers: self.source_deadline_peers.load(Ordering::Relaxed),
            announce_attempts: self.announce_attempts.load(Ordering::Relaxed),
            announce_success: self.announce_success.load(Ordering::Relaxed),
            tcp_attempts: self.tcp_attempts.load(Ordering::Relaxed),
            utp_attempts: self.utp_attempts.load(Ordering::Relaxed),
            tcp_connect_ok: self.tcp_connect_ok.load(Ordering::Relaxed),
            utp_connect_ok: self.utp_connect_ok.load(Ordering::Relaxed),
            tcp_metadata_ok: self.tcp_metadata_ok.load(Ordering::Relaxed),
            utp_metadata_ok: self.utp_metadata_ok.load(Ordering::Relaxed),
            tcp_connect_actual: self.tcp_connect_actual.load(Ordering::Relaxed),
            utp_connect_actual: self.utp_connect_actual.load(Ordering::Relaxed),
            connect_ok_no_metadata: self.connect_ok_no_metadata.load(Ordering::Relaxed),
            metadata_failed_io: self.metadata_failed_io.load(Ordering::Relaxed),
            metadata_failed_silent: self.metadata_failed_silent.load(Ordering::Relaxed),
            metadata_timeout: self.metadata_timeout.load(Ordering::Relaxed),
            walker_steps: self.walker_steps.load(Ordering::Relaxed),
            walker_queries: self.walker_queries.load(Ordering::Relaxed),
            walker_ok: self.walker_ok.load(Ordering::Relaxed),
            walker_nodes_returned: self.walker_nodes_returned.load(Ordering::Relaxed),
            walker_self_target: self.walker_self_target.load(Ordering::Relaxed),
            walker_random_target: self.walker_random_target.load(Ordering::Relaxed),
            walker_sybil_target: self.walker_sybil_target.load(Ordering::Relaxed),
            routing_insert_calls: self.routing_insert_calls.load(Ordering::Relaxed),
            routing_nodes_added: self.routing_nodes_added.load(Ordering::Relaxed),
            routing_buckets_used: self.routing_buckets_used.load(Ordering::Relaxed),
            routing_new_ids: self.routing_new_ids.load(Ordering::Relaxed),
            routing_rejected: self.routing_rejected.load(Ordering::Relaxed),
            log_dropped: self.log_dropped.load(Ordering::Relaxed),
        }
    }
}
