[Interface]
Address = 10.99.0.3/24
PrivateKey = 8LypufsQSY0m0ZvFDVp91qB8sxCilCCYQowIHo0ZyUQ=

[Peer]
PublicKey = LfB0IekKDbeacUYMdlYYzHiOHXsI+6ssdZafcOlbQF4=
Endpoint = 127.0.0.1:51820
AllowedIPs = 10.99.0.0/24
PersistentKeepalive = 25
